uvicorn
fastapi
python-multipart
email-validator
requests
celery
passlib
tenacity
pydantic
emails
raven
gunicorn
jinja2
psycopg2-binary
alembic
sqlalchemy
pytest
python-jose
aiofiles
openpyxl
python-socketio
psutil
